name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - feature/6--github-cicd

jobs:
  deploy:
    if: github.ref == 'refs/heads/feature/6--github-cicd'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Repository 파일 목록 출력
        run: |
          echo "Listing files in the repository:"
          ls -la

      - name: install & build
        run: |
          echo "Building the project..."
          npm install
          npm run build

      - name: Build files 목록 출력
        run: |
          echo "Listing files in the build directory:"
          ls -la ./dist

      - name: AWS Resource
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to S3
        run: |
          echo "Deploying to S3..."
          aws s3 sync ./dist s3://oz-frontend-team2 --delete
          aws s3 cp ./dist/index.html s3://oz-frontend-team2 --metadata-directive REPLACE --cache-control "no-cache"

      - name: Invalidate CloudFront Cache
        run: |
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation --distribution-id E22MTX5W58G0EE --paths "/*"

      - name: Notify Deployment Success
        run: |
          echo "Deployment to S3 and CloudFront completed successfully!"
          echo "You can access your site at https://oz-team2.kro.kr/"
